app/urls.py
from django.contrib import admin
from django.urls import path
from app import views

urlpatterns = [
    path('emp', views.home),  
    path('show',views.show),
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
]

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("app.urls"))
]

app/models.py
from django.db import models

# Create your models here.
 
class Employee(models.Model):  
    eid = models.CharField(max_length=20)  
    ename = models.CharField(max_length=100)  
    eemail = models.EmailField()  
    econtact = models.CharField(max_length=15)  
    class Meta:  
        db_table = "employ"  

app/forms.py
from django import forms  
from app.models import Employee  
class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = "__all__"  

app/views.py
from django.shortcuts import render,redirect

from app.forms import EmployeeForm
from app.models import Employee

# Create your views here.

def home(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = EmployeeForm()
    return render(request, 'index.html', {'form': form})

def show(request):
    employees = Employee.objects.all()
    return render(request, "show.html", {'employees': employees})


def edit(request, id):  
    employee = Employee.objects.get(id=id)  
    return render(request,'edit.html', {'employee':employee})  


def update(request, id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance=employee)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, 'edit.html', {'employee': employee})


def destroy(request, id):  
    employee = Employee.objects.get(id=id)  
    employee.delete()  
    return redirect("/show")  

app/templates/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS v5.2.1 -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>

  <body>
    <form method="POST" class="post-form" action="/update/{{employee.id}}">
      {% csrf_token %}
      <div class="container">
        <br />
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <h3>Update Details</h3>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Id:</label>
          <div class="col-sm-4">
            <input
              type="text"
              name="eid"
              id="id_eid"
              required
              maxlength="20"
              value="{{ employee.eid }}"
            />
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Name:</label>
          <div class="col-sm-4">
            <input
              type="text"
              name="ename"
              id="id_ename"
              required
              maxlength="100"
              value="{{ employee.ename }} "
            />
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Email:</label>
          <div class="col-sm-4">
            <input
              type="email"
              name="eemail"
              id="id_eemail"
              required
              maxlength="254"
              value="{{ employee.eemail }}"
            />
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Contact:</label>
          <div class="col-sm-4">
            <input
              type="text"
              name="econtact"
              id="id_econtact"
              required
              maxlength="15"
              value="{{ employee.econtact }}"
            />
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <button type="submit" class="btn btn-success">Update</button>
          </div>
        </div>
      </div>
    </form>

    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
      integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

app/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS v5.2.1 -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>

  <body>
       <form method="POST" class="post-form" action="/emp">
      {% csrf_token %}
      <div class="container">
        <br />
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <h3>Enter Details</h3>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Id:</label>
          <div class="col-sm-4">{{ form.eid }}</div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Name:</label>
          <div class="col-sm-4">{{ form.ename }}</div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Email:</label>
          <div class="col-sm-4">{{ form.eemail }}</div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Contact:</label>
          <div class="col-sm-4">{{ form.econtact }}</div>
        </div>
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
      </div>
    </form>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
      integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

app/templates/show.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Employee Records</title>
    <link rel="stylesheet" href="{% static 'css/show.css' %}" />
    {% comment %} font awsom {% endcomment %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
    <table
      class="container mt-3 table table-striped table-bordered table-warning table-lg"
    >
      <thead class="thead-dark">
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Email</th>
          <th>Contact</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for employee in employees %}
        <tr>
          <td>{{ employee.eid }}</td>
          <td>{{ employee.ename }}</td>
          <td>{{ employee.eemail }}</td>
          <td>{{ employee.econtact }}</td>
          <td>
            <a href="/edit/{{ employee.id }}"
              ><span class="glyphicon glyphicon-pencil"> <i class="fa fa-pencil" aria-hidden="true"></i> </span></a
            >
            <a href="/delete/{{ employee.id }}"><i class="fa fa-trash" aria-hidden="true"></i></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <br />
    <br />
    <a href="/emp" class="btn btn-primary">Add New Record</a>
  </body>
</html>